services:
  pdb:
    image: pdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"         # Maps container port 8080 (ASP.NET Core default) to host port 5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Adjust the connection string to point to the 'db' service
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=pdb;Username=postgres;Password=secret
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
